### ISSUE TITLE
test.exe is not an exe file

### ISSUE THREAD

**Issue by easrng** [LLK/scratch-asset-types#13]
### Expected Behavior

Running `test.exe` should succeed, because `test.exe` is a Windows executable.

### Actual Behavior

`test.exe` is a WebP file and so it cannot be run as a Windows executable,

### Steps to Reproduce

1. Clone the repo on a Windows computer
2. Attempt to run `test/fixtures/test.exe`
3. See error

### System Details
This issue is only applicable to Windows computers.

**Comment by colbygk** [comment]
It does not matter if it is or isn't in the current environment. The underlying issue is that anything.exe can be uploaded regardless of what's in it.
